############################################################################################
## This code define DFBMC class, single-process only
##
## Following input files are needed:
## 1. info including symmetric information
## 2. scf.out including irr k points
## 3. tt_geninterp.dat for wannier band energy
## 4. datasets generated by trans_reader.py
##
## 09/24/2019 -cz
############################################################################################

import numpy as np 
import matplotlib.pyplot as plt
import copy 
from math import pi, floor 
import scipy.stats as rn 
import sys 
import multiprocessing  

class MCseries:
    """This class defines a series Discrete-Full-Band-Monte-Carlo(DFBMC) calculation that
    share same data sets."""
    def __init__(self, NK, NBND, NBNDv, reci_vec, prefix='./', test_mode=0, 
    nelec=1, ds_file=None, wan_file=None, scf_file=None, trans_file=None, Wan_Band_List=[0],
    selfscat=1, stat_e=None, plot_e=None, stat_kx=None, plot_kx=None, 
    stat_bnd=None, stat_kint=None, stat_v=None, stat_t=None, restart=2, pltsave=0, 
    infiles_generate=0, irrbz=0, sp_fermi=0, elecf_list=None, totstep=None, scut=1e-9,
    output='std', enable_para=False, Nprocess=1, iverbosity=None):
        """ Initialize input parameters.

        NK: int
            number of k points in one dimension
        NBND: int
            number of bands
        NBNDv: int
            number of bands in velocity files
        reci_vec: ndarray(2,2)
            reciprocal vector of 2D lattice
        prefix: string
            prefix of datasets
        test_mode: int
            if test_mode == 1, all test codes will be performed
            if test_mode == 2, portions of test codes
            if test_mode == 3, efficiency test
            if test_mode == 4, memory test
        nelec: int
            number of electrons
        ds_file: string
            name of transition rate dataset files
        wan_file: string
            name of wannier interpolation velocity files
        scf_file: string
            name of scf.out
        Wan_Band_List: list of int
            selected band index in wannier interpolation velocity
        selfscat: int
            0 for not to use self-scattering techniques
            1 for to use
        stat_e: int 
            1 for to store energy step by step 
        stat_kx: int
            1 for to store k position step by step
            2 for also to store length of deltak step by step
        plot_kx: int
            1 for to plot arrows
            2 for to plot scatters
        plot_e: int
            1 for to plot by time-sequence
            2 for to plot by hist
            3 for to plot by hist and to print average energy
            4 for to only calculate average energy
        stat_bnd: int
            1 for to store band index for each step
        stat_kint: int
            1 for to store k index for each step 
        stat_v: int
            1 for to store velocity step by step
            2 for to calculate average velocity
            3 for to calculate averaged velocity between initial and final states
        stat_t: int
            0 for not to use time-weighted average in statistics
            1 for to store stpe-by-step lifetime, also draw pictures by real time
        restart: int
            0 for not to use restart mode
            1 for to write trans, index, scat matrix in files
            2 for to read trans, index, scat matrix from files
        pltsave: int
            0 for to show pictures 
            1 for to save pictures in jpg
        infiles_generate: int
            1 for to generate wannier and epw points
        irrbz: int
            0 for to use full Brillouin zone
            1 for to use irreducible Brillouin zone for trans, index and scat matrix
            only compatible with selfscat == 1
        sp_fermi: int
            1 for to use lowest band energy as fermi energy 
            2 for to use highest band energy as fermi energy
        elecf_list: ndarray(n,2)
            electric field list used in calculation
        totstep: int
            Number of MC steps used in one MC simulation.
        scut: float
            Cutoff of transition rate. 1e-9 should be safe for NK<300. 
        output: string
            print function will re-directed to output file. 'std' will stand for sys.stdout.
        enable_para: bool
            Ture for enable parallel MC simulation.
        Nprocess: int
            Number of process to enable parallel MC simulations.
        iverbosity: int
            whether to output full information
        """

        ## Here we start to initialize the control parameters
        self.NK = NK
        self.NKtot = NK*NK
        self.NBND = NBND
        self.NBNDv = NBNDv 
        self.reci_vec = 2*pi*np.array(reci_vec)
        self.inv_reci_vec = np.linalg.inv(self.reci_vec)
        prefix = str(prefix).strip()
        if prefix[-1] is '/':
            self.prefix = prefix
        else:
            self.prefix = prefix+'/'

        self.test_mode = test_mode 

        if test_mode == 3:
            from profile import Profile  
        elif test_mode == 4:
            import tracemalloc
            tracemalloc.start()

        self.nelec = nelec 

        if ds_file is None:
            self.ds_file = self.prefix+'ds'
        else:
            self.ds_file = self.prefix+ds_file 

        if wan_file is None:
            self.wan_file = self.prefix+'tt_geninterp.dat'
        else:
            self.wan_file = self.prefix+wan_file 
        
        if scf_file is None:
            self.scf_file = self.prefix+'scf.out'
        else:
            self.scf_file = self.prefix+scf_file 

        if trans_file is None:
            self.trans_file = self.prefix+'fort.708'
        else:
            self.trans_file = self.prefix+trans_file 

        self.Wan_Band_List = np.array(Wan_Band_List)
        self.selfscat = selfscat 
        if selfscat == 1:
            self.scat_total = 0.3

        self.totstep = 10000
        self.iverbosity = 1
        if test_mode in [0, 3, 4]:
            self.stat_e = 1
            self.plot_e = 4
            self.stat_kx = 0
            self.plot_kx = 0
            self.stat_bnd = 0
            self.stat_kint = 0
            self.stat_v = 3
            self.stat_t = 1
            self.pltsave = 0
            self.totstep = 30000
            self.iverbosity = 0
        elif test_mode == 1:
            self.stat_e = 1
            self.plot_e = 1
            self.stat_kx = 1
            self.plot_kx = 1
            self.stat_bnd = 1
            self.stat_kint = 1
            self.stat_v = 1
            self.stat_t = 1
            self.pltsave = 0
            self.totstep = 100
            self.iverbosity = 1
        elif test_mode == 2:
            self.stat_e = 1
            self.plot_e = 3
            self.stat_kx = 1
            self.plot_kx = 2
            self.stat_bnd = 0
            self.stat_kint = 0
            self.stat_v = 3
            self.stat_t = 1
            self.pltsave = 0
            self.totstep = 10000
            self.iverbosity = 1
        
        if stat_e:
            self.stat_e = stat_e 
        if plot_e:
            self.plot_e = plot_e
        if stat_kx:
            self.stat_kx = stat_kx 
        if plot_kx:
            self.plot_kx = plot_kx 
        if stat_bnd:
            self.stat_bnd = stat_bnd
        if stat_kint:
            self.stat_kint = stat_kint 
        if stat_v:
            self.stat_v = stat_v 
        if stat_t:
            self.stat_t = stat_t 
        if totstep:
            self.totstep = totstep 
        if enable_para:
            self.totstep = self.totstep - self.totstep%Nprocess 
        if iverbosity:
            self.iverbosity = iverbosity

        self.restart = restart 
        self.pltsave = pltsave 
        self.infiles_generate = infiles_generate 
        self.irrbz = irrbz 
        self.sp_fermi = sp_fermi
        if elecf_list is None and test_mode in [1,3,4]:
            self.elecf_list = [[30e6,0]]
        elif elecf_list is None and test_mode == 2:
            self.elecf_list = np.array([[0,0],[3e5,0],[6e5,0],[15e5,0],[3e6,0],
            [7e6,0],[13e6,0],[20e6,0],[30e6,0]])
        elif elecf_list is None:
            self.elecf_list = np.array([[0,0],[1e5,0],[3e5,0],[6e5,0],[10e5,0],
            [15e5,0],[2e6,0],[3e6,0],[4e6,0],[7e6,0],[10e6,0],[13e6,0],
            [16e6,0],[20e6,0],[25e6,0],[30e6,0]])
        else: 
            self.elecf_list = np.array(elecf_list)
        self.scut = scut

        if output[0:3] == 'std':
            self.fout = sys.stdout 
        else: 
            try:
                self.fout = open(self.prefix+output, 'w') 
                self.foutname = self.prefix+output
            except:
                raise Exception("Cannot redirect ouput files.")

        self.enable_para = enable_para 
        self.Nprocess = Nprocess 

        ## Here we introduce work variables in class
        self.ELECF = np.zeros((2, ))
        # electric field in x-y dimension, should between 0~3e6 
        self.cbnd = np.zeros((self.nelec, ), dtype=int)
        # current band index
        self.ckint = np.zeros((self.nelec, ), dtype=int)
        # current k index
        self.clifetime = np.zeros((self.nelec, ))
        # current lifetime 
        self.ckfx = np.zeros((self.nelec, 2))
        # current electron k-space fractional coordinates
        self.bande = np.zeros((self.NKtot, self.NBND))
        # bande energy
        self.velocity = np.zeros((self.NKtot, self.NBND, 3))
        # wannier interpolated band velocity
        self.trans = []
        # transition rate matrix
        self.index = []
        # index of transition rete
        self.scat = []
        # scattering rate of each k points


        ## Here we introduce statistics data
        self.sbs_energy = []
        self.sbs_n = 0
        self.sbs_time = []
        self.sbs_velocity = []
        self.sbs_kx = [] 
        self.tot_time = np.zeros((self.nelec, ))
        self.avg_velocity = np.zeros((self.nelec, 2))
        self.sbs_bnd = []
        self.sbs_kint = []

        if self.stat_kx == 2:
            self.sbs_lendk = []
        if self.stat_v == 3:
            self.lastv = np.zeros((self.nelec, 2))
        if self.irrbz == 1:
            self.bz2ibz = []
            self.bz_sym = []
            self.sym_matrix = []
            self.irrwk = []

        self.res_series = []

    
    def init_check(self):
        """Check whether variables in __init__ are compatible."""
        if not (self.enable_para and self.test_mode == 0):
            raise Exception("Error: parallel only function when test_mode == 0.")

        if self.enable_para and (self.fout is sys.stdout):
            raise Exception("Error: parallel only function when output redirected to files.")
        

    ## Frequently used small functions 
    def kindex_add(self, ik, iq):
        NK = self.NK
        iky = ik%NK 
        ikx = ik//NK 
        iqy = iq%NK
        iqx = iq//NK 

        jky = (iky+iqy)%NK 
        jkx = (ikx+iqx)%NK 

        return jkx*NK + jky 

    def get_kfrac(self, ik_list):
        NK = self.NK 
        kcart_list = np.zeros((len(ik_list),2))
        for ik in range(len(ik_list)):
            kcart_list[ik][0] = float(ik_list[ik]//NK)/NK 
            kcart_list[ik][1] = float(ik_list[ik]%NK)/NK 

        return kcart_list        

    def get_kindex(self, kfrac_list):
        NK = self.NK
        ik_list = np.zeros((len(kfrac_list),), dtype=int)
        for ik in range(len(kfrac_list)): 
            ikx = floor(kfrac_list[ik][0] * NK) 
            iky = floor(kfrac_list[ik][1] * NK) 
            ik_list[ik] = iky + ikx * NK 

        return ik_list 

    def get_kindex2(self, kfrac_list):
        NK = self.NK
        ik_list = np.zeros((len(kfrac_list),), dtype=int)
        for ik in range(len(kfrac_list)): 
            ikx = int(round(kfrac_list[ik][0] * NK))%NK
            iky = int(round(kfrac_list[ik][1] * NK))%NK
            ik_list[ik] = iky + ikx * NK 

        return ik_list 

    def floor_list(self, in_ndarray):
        out_ndarray = in_ndarray.reshape(-1).copy()
        for i in range(len(out_ndarray)):
            out_ndarray[i] = out_ndarray[i] - floor(out_ndarray[i])

        out_ndarray = np.reshape(out_ndarray, np.shape(in_ndarray))

        return out_ndarray

    def cart2frac(self, kcart_list):
        kfrac_list = np.zeros((len(kcart_list),2))
        for ik in range(len(kcart_list)):
            kfrac_list[ik][0], kfrac_list[ik][1] = np.dot(kcart_list[ik], self.inv_reci_vec)

        return kfrac_list

    def frac2cart(self, kfrac_list):
        kcart_list = np.zeros(np.shape(kfrac_list))
        for ik in range(len(kfrac_list)):
            kcart_list[ik][0], kcart_list[ik][1] = np.dot(kfrac_list[ik], self.reci_vec)

        return kcart_list    



    ## Functions to read
    def reader_velocity(self):
        """Read bande energy and group velocity in wan_file."""
        velocity = np.zeros((self.NKtot, self.NBND, 3))
        bande = np.zeros((self.NKtot, self.NBND))

        try:
            fo = open(self.wan_file, 'r')
        except FileNotFoundError:
            print(self.wan_file+" not exists.")

        bnd_min = np.min(self.Wan_Band_List)
        for ik in range(self.NKtot):
            for ibnd in range(self.NBNDv):
                line = fo.readline()

                if (line[0] == '#'):
                    line = fo.readline()
                    line = fo.readline()
                    line = fo.readline()

                if ibnd in self.Wan_Band_List:
                    line = line.split()

                    # if (ibnd == 0):
                    #     kvec[ik][0] = float(line[1])
                    #     kvec[ik][1] = float(line[2])
                    #     kvec[ik][2] = float(line[3])
                    
                    bande[ik][ibnd-bnd_min] = float(line[4])

                    velocity[ik][ibnd-bnd_min][0] = float(line[5])
                    velocity[ik][ibnd-bnd_min][1] = float(line[6])
                    velocity[ik][ibnd-bnd_min][2] = float(line[7])

        fo.close()

        self.velocity = velocity 
        if self.sp_fermi == 1:
            self.bande = bande - np.min(bande)
        elif self.sp_fermi == 2:
            self.bande = bande - np.max(bande) 
        else:
            self.bande = bande 

    def reader_scfout(self, ndim=2):
        """Read irr k points position, weight from scf_file, 
        and read symmetric matrix from info"""
        try:
            fo = open(self.scf_file, 'r')
        except FileNotFoundError:
            print(self.scf_file+" not exists.")

        line = fo.readline()
        while line:        
            line = line.split()
            if not line:
                line = fo.readline()
                continue

            if line[0] == 'number' and line[3] == 'points=':
                nirrk = int(line[4])
                irrckx = np.zeros((nirrk, 3))
                irrwk = np.zeros((nirrk, ))

                line = fo.readline()
                for i in range(nirrk):
                    line = fo.readline().replace('(', ' ').replace(')', ' ').split()
                    irrckx[i][0] = float(line[3])
                    irrckx[i][1] = float(line[4])
                    irrckx[i][2] = float(line[5])
                    irrwk[i] = float(line[9])


                irrfkx = np.zeros((nirrk, 3))
                line = fo.readline()
                line = fo.readline()
                for i in range(nirrk):
                    line = fo.readline().replace('(', ' ').replace(')', ' ').split()
                    irrfkx[i][0] = float(line[3])
                    irrfkx[i][1] = float(line[4])
                    irrfkx[i][2] = float(line[5])

            line = fo.readline()
        fo.close()
        
        try:
            fo = open('info', 'r')
        except FileNotFoundError:
            print("info not exists")
        line = fo.readline()
        while line:
            line = line.split()
            if not line:
                line = fo.readline()
                continue

            if line[1] == 'symmetry':
                nsym = int(line[0])
                sym_matrix = np.zeros((nsym, 3, 3))
                for i in range(nsym//6):
                    line = fo.readline()
                    line = fo.readline().split()
                    sym_matrix[i*6:(i+1)*6, 0] = np.reshape([int(s) for s in line], (6,3))
                    line = fo.readline().split()
                    sym_matrix[i*6:(i+1)*6, 1] = np.reshape([int(s) for s in line], (6,3))
                    line = fo.readline().split()
                    sym_matrix[i*6:(i+1)*6, 2] = np.reshape([int(s) for s in line], (6,3))
                
                if nsym%6 != 0:
                    tmp = nsym%6
                    line = fo.readline()
                    line = fo.readline().split()
                    sym_matrix[i*6:i*6+tmp, 0] = np.reshape([int(s) for s in line], (tmp,3))
                    line = fo.readline().split()
                    sym_matrix[i*6:i*6+tmp, 1] = np.reshape([int(s) for s in line], (tmp,3))
                    line = fo.readline().split()
                    sym_matrix[i*6:i*6+tmp, 2] = np.reshape([int(s) for s in line], (tmp,3))

            line = fo.readline()
        fo.close()

        if ndim == 2:
            self.sym_matrix = sym_matrix[:,0:2,0:2]
            # self.irrckx = irrckx[:,0:2]
            self.irrfkx = irrfkx[:,0:2]
            self.irrwk = irrwk 
        else:
            self.sym_matrix = sym_matrix
            self.irrfkx = irrfkx
            self.irrwk = irrwk 

    def do_chunk(self, chunk, scut=1E-10):  
        """Process a chunk of transition rate file from epw."""
        nk = self.NK 
        nbnd = self.NBND
        nline = int(len(chunk)/36)
        trans = [[[] for _ in range(nbnd)] for _ in range(nk) ]
        index = [[[] for _ in range(nbnd)] for _ in range(nk) ]  

        for i in range(nline):
            ttmp = float(chunk[15+i*36:35+i*36])
            if ttmp > scut:
                ik = int(chunk[5+i*36:10+i*36]) - 1
                ijbnd = int(chunk[10+i*36:15+i*36]) - 1
                ibnd = ijbnd//nbnd 

                # jk = kindex_add(ik, int(chunk[0+i*36:5+i*36])-1) 
                jk = int(chunk[0+i*36:5+i*36]) - 1

                trans[ik][ibnd].append(ttmp)
                index[ik][ibnd].append([jk, ijbnd%nbnd]) 

        return trans, index 

    def writer_data(self):
        """write 3 ndarray object to .npy files"""
        prefix = self.ds_file
        np.save(prefix+"_trans.npy", self.trans)
        np.save(prefix+"_index.npy", self.index)
        np.save(prefix+"_scat.npy", self.scat)

    def reader_restart(self):
        """read 3 ndarray object from .npy files"""
        prefix = self.ds_file
        try:
            self.trans = np.load(prefix+"_trans.npy", allow_pickle=True)
            self.index = np.load(prefix+"_index.npy", allow_pickle=True)
            self.scat = np.load(prefix+"_scat.npy", allow_pickle=True)
        except FileNotFoundError:
            print(prefix+"*.npy not exist.")

 
    def reader_trans(self):
        """The main function to read and process transtion rate files from epw."""
        nk = self.NK 
        nbnd = self.NBND 
        if self.restart == 0 or self.restart == 1:
            scat = np.zeros((nk, nbnd))

            trans = [[[] for _ in range(nbnd)] for _ in range(nk) ]
            index = [[np.zeros((0,2), dtype=int) for _ in range(nbnd)] for _ in range(nk) ] 
            
            try:
                fo = open(self.trans_file, 'r')
            except FileNotFoundError:
                print(self.trans_file+" not exists.")

            chunk_count = 1
            while True:
                chunk = fo.read(36*1000000) # 36*1e5 approximately 3.6MB 
                
                if chunk_count%5 == 0:
                    print("read size ~ ", chunk_count*3.433227539e1, " MB", file=self.fout)

                chunk_count += 1

                if not chunk:
                    break 

                trans_tmp, index_tmp = self.do_chunk(chunk, self.scut) 
                for ik in range(nk):
                    for ibnd in range(nbnd):
                        trans[ik][ibnd] = np.append(trans[ik][ibnd], trans_tmp[ik][ibnd])
                        if index_tmp[ik][ibnd]:
                            index[ik][ibnd] = np.append(index[ik][ibnd], index_tmp[ik][ibnd], axis=0)



            for ik in range(nk):
                for ibnd in range(nbnd):
                    trans[ik][ibnd] = np.array(trans[ik][ibnd])*13.6
                    index[ik][ibnd] = np.array(index[ik][ibnd],dtype=int)
                    # trans format: [ik](list)[ibnd](list)[trans_rate](array)
                    # index format: [ik](list)[ibnd](list)[iq, jbnd](array)

                    scat[ik][ibnd] = np.sum(trans[ik][ibnd])

                    trans[ik][ibnd] = trans[ik][ibnd] / scat[ik][ibnd] 

                # trans[ik] = np.array(trans[ik])

            trans = np.array(trans)

            fo.close()

            self.trans = trans
            self.index = index
            self.scat = scat 
            if self.restart == 1:
                self.writer_data()
        elif self.restart == 2:
            self.reader_restart()


    ## Here we introduce relatively large functions used in DFBMC
    def free_flight(self):
        """
        Carrier is accelerated by electric field.

        The first part contains non-self-scattering free flight process.
        The second part used self-scattering method to accurately simulate free 
        flight process. Irreducible k q points method is implemented. 
        """
        if self.selfscat == 0:
            scat_list = self.scat[self.ckint, self.cbnd]
            self.clifetime = -1.0/scat_list * np.log(np.random.rand(self.nelec))

            deltkfx = np.array([self.clifetime]).T*self.ELECF/2 * 1e-10

            if self.stat_kx == 2:
                os_lendk = []
                for dk in deltkfx:
                    os_lendk.append(np.linalg.norm(dk))
                self.sbs_lendk.append(os_lendk)

            deltkfx = self.cart2frac(deltkfx)
            self.ckfx = self.floor_list(deltkfx + self.ckfx) 

            self.ckint = self.get_kindex(self.ckfx)

        elif self.selfscat == 1:
            if self.stat_kx == 2:
                os_lendk = []
            for ie in range(self.nelec):
                lendk_tmp = 0.0
                clifetime_tmp = 0.0

                ik = self.ckint[ie]
                ibnd = self.cbnd[ie]
                if self.irrbz == 0:
                    iscat = self.scat[ik][ibnd]
                elif self.irrbz == 1:
                    iscat = self.scat[self.bz2ibz[ik]][ibnd]
                ikfx = self.ckfx[ie] 

                while True:
                    clt_atp = -1.0/self.scat_total * np.log(np.random.rand())
                    clifetime_tmp += clt_atp 

                    deltkfx = clt_atp *self.ELECF/2 * 1e-10
                    if self.stat_kx == 2:
                        lendk_tmp += np.linalg.norm(deltkfx)

                    deltkfx = self.cart2frac([deltkfx])[0]
                    ikfx = self.floor_list(deltkfx + ikfx)
                    ik = self.get_kindex([ikfx])[0]
                    if self.irrbz == 0:
                        iscat = self.scat[ik][ibnd]
                    elif self.irrbz == 1:
                        iscat = self.scat[self.bz2ibz[ik]][ibnd] 

                    if np.random.rand()*self.scat_total < iscat:
                        break 

                if self.stat_kx == 2:
                    os_lendk.append(lendk_tmp)
                self.clifetime[ie] = clifetime_tmp
                self.ckfx[ie] = ikfx 
                self.ckint[ie] = ik 

            if self.stat_kx == 2:
                self.sbs_lendk.append(os_lendk) 

    def scattering(self):
        """
        Randomly choose a final state from transition rate matrix.

        irreducible brilliouin zone method is implemented.
        """
        if self.irrbz == 0:
            for ie in range(self.nelec):
                ik = self.ckint[ie]
                ibnd = self.cbnd[ie]

                xk = np.arange(len(self.trans[ik][ibnd]))
                custm = rn.rv_discrete(values=(xk, self.trans[ik][ibnd]))

                itmp = custm.rvs()
                iq, jbnd = self.index[ik][ibnd][itmp]

                qfrac = self.get_kfrac([iq])[0]
                self.ckfx[ie] = self.floor_list(qfrac+self.ckfx[ie])

                self.ckint[ie] = self.get_kindex([self.ckfx[ie]])[0]
                self.cbnd[ie] = jbnd 

                self.clifetime[ie] = 0.0 
        elif self.irrbz == 1:
            for ie in range(self.nelec):
                ik = self.ckint[ie]
                ibnd = self.cbnd[ie]

                xk = np.arange(len(self.trans[self.bz2ibz[ik]][ibnd]))
                custm = rn.rv_discrete(values=(xk, self.trans[self.bz2ibz[ik]][ibnd]))

                itmp = custm.rvs()
                iq, jbnd = self.index[self.bz2ibz[ik]][ibnd][itmp]

                qfrac = np.dot(self.sym_matrix[self.bz_sym[ik]], self.get_kfrac([iq])[0])
                self.ckfx[ie] = self.floor_list(qfrac+self.ckfx[ie])

                self.ckint[ie] = self.get_kindex([self.ckfx[ie]])[0]
                self.cbnd[ie] = jbnd

                self.clifetime[ie] = 0.0 


    def kmap_array(self):
        """
        Create k points map from full-bz to irr-bz.

        Update self.bz2ibz and self.bz_sym.
        self.bz2ibz contains k index map from full-bz to irr-bz.
        self.bz_sym contains rotation matrix index to rotate a vector from ibz to fbz.
        """ 
        self.bz2ibz = np.ones((self.NKtot, ), dtype=int)*-1
        self.bz_sym = np.ones((self.NKtot, ), dtype=int)*-1

        nirrk = len(self.irrfkx)
        nsym = len(self.sym_matrix)

        for irrk in range(nirrk):
            p2bz_ckx = np.array([np.dot(self.sym_matrix[i], self.irrfkx[irrk]) for i in range(nsym)])
            p2bz_ik = self.get_kindex2(p2bz_ckx)

            self.bz2ibz[p2bz_ik] = irrk 
            self.bz_sym[p2bz_ik] = np.arange(nsym)

        
        if -1 in self.bz2ibz or -1 in self.bz_sym:
            raise Exception("Error: in ibz and full bz k points match.")


    def MC_init(self, ELECFin=[3e6,0]):
        """
        Initialize work variables for each MC under certain electric field.

        Assign random k positions and band index for carrier.
        Update carriers' k point index.
        Initialize electric field.
        """
        self.clifetime = np.zeros((self.nelec, ))

        self.cbnd[:] = 0
        # assign band index =0 to start from a lower energy.

        if self.test_mode == 1:
            self.ckfx[:,:] = 0.001
        else:
            # self.ckfx = np.random.rand(self.nelec, 2)
            self.ckfx[:,:] = 0.34

        self.ckint = self.get_kindex(self.ckfx)

        if self.stat_v == 3:
            self.lastv = np.zeros((self.nelec, 2))

        self.ELECF = np.array(ELECFin)

        if self.selfscat == 1:
            if self.scat_total < np.max(self.scat):
                if self.iverbosity > 0:
                    print("Setting total scattering rate...", file=self.fout)
                self.scat_total = np.max(self.scat)*1.1
            if self.iverbosity > 0:
                print("total scattering rate is: ", self.scat_total, "max of actual scattering rate: ", 
                np.max(self.scat), file=self.fout)
        # Correctly set total scattering rate 


        # initialize statistics datasets
        self.sbs_energy = []
        self.sbs_n = 0
        self.sbs_time = []
        self.sbs_velocity = []
        self.sbs_kx = []
        self.tot_time = np.zeros((self.nelec, ))

        self.avg_velocity = np.zeros((self.nelec, 2))

        self.sbs_bnd = []
        self.sbs_kint = []
        if self.stat_kx == 2:
            self.sbs_lendk = []

    def output_infiles(self):
        """
        Generate tt_geninterp.kpt and kpt.dat used in wannier90 and epw.
        """
        nirrk = len(self.irrfkx)

        # write wannier input
        fw = open(self.prefix+'tt_geniterp.kpt', 'w')
        fw.write("The .rst line is a comment (its maximum allowed length is 500 characters).i\n")
        fw.write("crystal\n")
        fw.write("%i\n" %(nirrk))
        for i in range(nirrk):
            fw.write("%i %20.12f %20.12f %20.12f \n" %(i+1, self.irrfkx[i][0], self.irrfkx[i][1], 0.0))
        fw.close()

        # write epw k points input
        fw = open(self.prefix+'kpt.dat', 'w')
        fw.write("%i\n" %(nirrk))
        for i in range(nirrk):
            fw.write("  %20.12f %20.12f %20.12f %20.12f\n" %(self.irrfkx[i][0], self.irrfkx[i][1], 0.0, self.irrwk[i]))
        fw.close()

    def MC_stat(self):
        """
        Do statistics after each scattering and free flight event.
        """

        self.sbs_n += 1
        self.tot_time += self.clifetime 

        if self.stat_e == 1:
            os_energy = self.bande[self.ckint, self.cbnd]
            self.sbs_energy.append(os_energy.copy())

        if self.stat_v == 1:
            os_velocity = self.velocity[self.ckint, self.cbnd, 0:2]
            self.sbs_velocity.append(os_velocity.copy())
        elif self.stat_v == 2:
            if self.stat_t == 0:
                self.avg_velocity += self.velocity[self.ckint, self.cbnd, 0:2]
            elif self.stat_t ==1:
                self.avg_velocity[:,0] += np.multiply(self.clifetime, self.velocity[self.ckint, self.cbnd, 0])
                self.avg_velocity[:,1] += np.multiply(self.clifetime, self.velocity[self.ckint, self.cbnd, 1])
        elif self.stat_v == 3:
            if self.stat_t == 0:
                vtmp = (self.lastv + self.velocity[self.ckint, self.cbnd, 0:2])/2
                self.avg_velocity += vtmp
                self.lastv = copy.deepcopy(self.velocity[self.ckint, self.cbnd, 0:2])
            elif self.stat_t == 1:
                vtmp = (self.velocity[self.ckint, self.cbnd, 0:2] + self.lastv)/2
                self.avg_velocity[:,0] += np.multiply(self.clifetime, vtmp[:, 0])
                self.avg_velocity[:,1] += np.multiply(self.clifetime, vtmp[:, 1]) 
                self.lastv = copy.deepcopy(self.velocity[self.ckint, self.cbnd, 0:2])

        if self.stat_kx == 1:
            self.sbs_kx.append(copy.deepcopy(self.ckfx))

        if self.stat_t == 1:
            if self.sbs_n == 1:
                self.sbs_time.append(copy.deepcopy(self.clifetime))
            else:
                self.sbs_time.append(self.sbs_time[-1]+copy.deepcopy(self.clifetime)) 

        if self.stat_bnd == 1:
            self.sbs_bnd.append(copy.deepcopy(self.cbnd)) 
        if self.stat_kint == 1:
            self.sbs_kint.append(copy.deepcopy(self.ckint))

    def MC_plot(self, title='default title'):
        """
        Process the data saved and plot figure at the end of MC simulation step.
        
        Plot the figures that give a glance of MC simulation work conditions.
        Averaged energy, averaged velocity are calculated and restored in self.res_series
        in form of dict list. 
        Keys and values in dict: 
        'Ex(v/m)'         : float
        'Ey(v/m)'         : float
        'Energy(eV)'      : ndarray(self.nelec,)
        'Vx(cm/s)'        : ndarray(self.nelec,)
        'Vy(cm/s)'        : ndarray(self.nelec,)

        Note that stat_k, stat_bnd, stat_kint might not compatible with nelec>1.
        """
        stat_quantity = {}
        stat_quantity['Ex(v/m)'] = self.ELECF[0]
        stat_quantity['Ey(v/m)'] = self.ELECF[1]

        step_list = range(self.sbs_n)
        if self.stat_t == 1:
            sbs_tmp = np.array(self.sbs_time)
            sbs_tmp = sbs_tmp*6.5821e-4 *2    # eV^-1 to ps 
            weight_t = np.zeros((len(sbs_tmp),self.nelec))
            weight_t[0] = (sbs_tmp[1]-sbs_tmp[0])/2
            weight_t[-1] = (sbs_tmp[-1]-sbs_tmp[-2])/2
            weight_t[1:-1] = 0.5*(sbs_tmp[2:]-sbs_tmp[:-2])

        # plot electron energy step by step 
        if self.stat_e == 1 and self.plot_e == 1:
            if self.stat_t == 0:
                plt.plot(step_list, self.sbs_energy)
                plt.xlabel("monte carlo step")
            else:
                plt.plot(sbs_tmp, self.sbs_energy)
                plt.xlabel("total time/ps")
            plt.ylabel("Energy/eV")
            plt.title(title)
            plt.show()
            plt.close()
        elif self.stat_e == 1 and self.plot_e == 2:
            if self.stat_t == 0:
                plt.hist(np.reshape(self.sbs_energy,(-1)), bins=50)
            else:
                plt.hist(np.reshape(self.sbs_energy,(-1)), bins=50, weights=np.reshape(weight_t,(-1)))
            plt.xlabel("energy statistics/eV")
            plt.ylabel("counts")
            plt.title(title)
            plt.show() 
            plt.close() 
        elif self.stat_e == 1 and self.plot_e == 3:
            if self.stat_t == 0:
                tmp_e = np.sum(self.sbs_energy, axis=1)/len(self.sbs_energy)
                print(title+"; average energy: %f eV" %(tmp_e), file=self.fout)
                plt.hist(np.reshape(self.sbs_energy,(-1)), bins=50)
            else:
                # tmp_e = np.sum(np.multiply(sbs_energy, weight_t))/np.sum(weight_t)
                tmp_e = np.average(self.sbs_energy, axis=0, weights=weight_t)
                print(title+"; average energy: %f eV" %(tmp_e), file=self.fout)
                plt.hist(np.reshape(self.sbs_energy,(-1)), bins=50, weights=np.reshape(weight_t,(-1)))
            plt.xlabel("energy statistics/eV")
            plt.ylabel("counts")
            plt.title(title)
            plt.show() 
            plt.close() 

            stat_quantity['Energy(eV)'] = copy.deepcopy(tmp_e)
            # add average energy to statistic quantities of this turn
        elif self.stat_e == 1 and self.plot_e == 4:
            if self.stat_t == 0:
                tmp_e = np.sum(self.sbs_energy, axis=1)/len(self.sbs_energy)
            else:
                tmp_e = np.average(self.sbs_energy, axis=0, weights=weight_t)
            if self.iverbosity > 0:
                print(title+"; average energy: %f eV" %(tmp_e), file=self.fout)
            stat_quantity['Energy(eV)'] = copy.deepcopy(tmp_e)
            # add average energy to statistic quantities of this turn


        # plot electron k positions step by step
        if self.stat_kx == 1:
            plt.figure()
            tmpx = np.reshape(self.sbs_kx, (self.sbs_n, self.nelec, 2))
            tmpx = tmpx[:,0,:]
            tmpx = self.frac2cart(tmpx)
            if self.plot_kx == 1:
                plt.quiver(tmpx[:-1,0], tmpx[:-1,1], tmpx[1:,0]-tmpx[:-1,0], tmpx[1:,1]-tmpx[:-1,1], scale_units='xy', angles='xy', scale=1)
            elif self.plot_kx == 2:
                plt.scatter(tmpx[:,0], tmpx[:,1], s=3)
            plt.axis("equal")
            plt.xlabel("kx/A^-1")
            plt.ylabel("ky/A^-1")
            plt.title(title)
            plt.show()
            plt.close()

        if self.stat_v == 1: 
            tmp = np.reshape(self.sbs_velocity, (self.sbs_n, self.nelec, 2)) 
            tmp = tmp[:,0,:] 
            if self.stat_t == 0:
                plt.plot(step_list, tmp[:,0], label='x velocity') 
                plt.plot(step_list, tmp[:,1], label='y velocity') 
            else:
                plt.plot(sbs_tmp, tmp[:,0], label='x velocity')
                plt.plot(sbs_tmp, tmp[:,1], label='y velocity') 
            plt.legend() 
            plt.title(title)
            plt.show() 
            plt.close() 
        elif self.stat_v == 2 or self.stat_v == 3:
            # eV*A to cm/s
            eva2cms = 1.519267582e7 
            res_v = np.zeros((self.nelec, 2))
            if self.stat_t == 0:
                if self.iverbosity>0:
                    print("average velocity in x: \n", self.avg_velocity[:,0]/self.sbs_n*eva2cms, file=self.fout)
                    print("average velocity in y: \n", self.avg_velocity[:,1]/self.sbs_n*eva2cms, file=self.fout)
                res_v = self.avg_velocity/self.sbs_n*eva2cms 
            else:
                if self.iverbosity>0:
                    print("time average velocity in x: \n", self.avg_velocity[:,0]/self.tot_time*eva2cms, file=self.fout)
                    print("time average velocity in y: \n", self.avg_velocity[:,1]/self.tot_time*eva2cms, file=self.fout)
                res_v = self.avg_velocity/self.tot_time*eva2cms 

            stat_quantity['Vx(cm/s)'] = copy.deepcopy(res_v[:,0])
            stat_quantity['Vy(cm/s)'] = copy.deepcopy(res_v[:,1])


        if self.stat_bnd == 1:
            plt.plot(sbs_tmp, self.sbs_bnd) 
            plt.xlabel("total time/ps")
            plt.ylabel("band index")
            plt.title(title)
            plt.show() 
            plt.close() 

        if self.stat_kint == 1:
            plt.hist(np.reshape(self.sbs_kint,(-1)), bins=100)
            plt.xlabel("k index statistics")
            plt.ylabel("counts")
            plt.title(title)
            plt.show()
            plt.close()

            counttmp = np.array([np.sum(self.sbs_kint==i) for i in np.unique(self.sbs_kint)])
            print("most frequent k index: ", np.unique(self.sbs_kint)[np.argmax(counttmp)], file=self.fout)

        self.res_series.append(copy.deepcopy(stat_quantity)) 
 

    ## Small functions used by precise test.
    def printer(self):
        """Print exact conditions of first electron."""
        ik = self.ckint[0]
        ibnd = self.cbnd[0]
        ckx = self.frac2cart(self.ckfx)
        print("current k fractional coordinates: ", self.ckfx[0], file=self.fout)
        print("current k crystal coordinates: ", ckx[0], file=self.fout)
        print("current k index and band: ", ik, ibnd, file=self.fout)
        print("corner energy: ", self.bande[ik][ibnd], file=self.fout)

    def check_trans(self):
        """Check transition rate data."""
        for ik in range(len(self.trans)):
            for ibnd in range(len(self.trans[ik])):
                ienergy = self.bande[ik][ibnd]
                for fstate in range(len(self.trans[ik][ibnd])):
                    iq = self.index[ik][ibnd][fstate][0]
                    jbnd = self.index[ik][ibnd][fstate][1]
                    jk = self.kindex_add(ik, iq) 
                    jenergy = self.bande[jk][jbnd] 

                    deltE = abs(jenergy-ienergy)
                    if deltE > 0.5:
                        print("iq, ik, ibnd, jbnd: ", iq, ik, ibnd, jbnd, file=self.fout)
                        print("transition rate:", self.trans[ik][ibnd][fstate], file=self.fout)


    def check_velocity(self):
        """Calculate averaged velocity in whole bz."""
        avgvx = 0.0
        avgvy = 0.0 
        for ie in range(len(self.velocity)):
            for ibnd in range(len(self.velocity[0])):
                avgvx += self.velocity[ie][ibnd][0]/self.NKtot
                avgvy += self.velocity[ie][ibnd][1]/self.NKtot

        print("averaged velocity in x,y: ", avgvx, avgvy, file=self.fout) 

            
    def check_kpath(self): 
        """Calculate free flight related information."""
        sbs_tmp = np.array(self.sbs_lendk) 

        for oe in sbs_tmp.T:
            print("mean of delta k(1/A): ", np.mean(oe), ", which is: ", 
            np.mean(oe)/self.reci_vec[0][0], "of k lattice. ", file=self.fout)
            print("max of delta k(1/A): ", np.max(oe), ", which is: ", 
            np.max(oe)/self.reci_vec[0][0], "of k lattice. ", file=self.fout)

            plt.hist(oe, bins=100)
            plt.xlabel("delta k") 
            plt.ylabel("frequency") 
            plt.show() 
            plt.close() 

    ## Main functions in DFBMC
    def MCmain(self, ELECFin):
        """Do MC simulation under input electric field."""
        if self.test_mode == 4:
            import tracemalloc

        self.MC_init(ELECFin)

        if self.test_mode == 1:
            # self.check_trans()
            self.check_velocity()

        for itot in range(self.totstep):

            if (self.iverbosity>0) and ((itot+1)%(self.totstep//100) == 0):
                print(itot+1, ":", np.array(self.sbs_time[-1])*6.5821e-4*2, " ps", file=self.fout)
            if (self.test_mode == 4) and ((itot+1)%(self.totstep//10) == 0) :
                print(tracemalloc.get_traced_memory(), file=self.fout)
                snapshot = tracemalloc.take_snapshot()
                top_stats = snapshot.statistics('lineno')

                for stat in top_stats[:10]:
                    print(stat, file=self.fout)

            if self.test_mode == 1:
                print("free flight ...", file=self.fout)
                self.printer()
            self.MC_stat()

            self.scattering()

            if self.test_mode == 1:
                print("scattering ...", file=self.fout)
                self.printer()
            self.MC_stat()

            self.free_flight()

        self.MC_plot('E='+str(np.linalg.norm(ELECFin))+' V/m')
        if self.stat_kx == 2:
            self.check_kpath()

    def MCseries_printer(self, electron_avg=True):
        """Print final results of this series of MC simulation."""

        if electron_avg:
            for key in self.res_series[0].keys():
                print(key, end='    ', file=self.fout)
            print(' ', file=self.fout)

            for res_d in self.res_series:
                for key in self.res_series[0].keys():
                    print(str(np.sum(res_d[key])), end='   ', file=self.fout)
                print(' ', file=self.fout)

    def MC_para(self):
        """
        This function helps set parallel environment.

        reset self.totstep
        redirect output file
        reset random seed
        do series of MC simulation under different 
        return self.res_series
        """
        self.totstep = self.totstep//self.Nprocess
        mpname = multiprocessing.current_process().name
        if self.iverbosity>0:
            try:
                mpfoutname = self.foutname+mpname+'.out'
                self.fout = open(mpfoutname, 'w')
            except:
                print(mpfoutname+" cannot be created.")
        np.random.seed()

        for i in range(len(self.elecf_list)):
            self.MCmain(self.elecf_list[i])

        return self.res_series

    def __getstate__(self):
        """Remove file object before pickling."""
        state = self.__dict__.copy()
        del state['fout']
        return state 

    def __setstate__(self, state):
        """Called while unpickling."""
        self.__dict__.update(state)

    def gather_para(self, res_l):
        """Gather parallel computation results and average them."""
        newres_l = []
        for ief in range(len(res_l[0])):
            newres = {}
            for key in res_l[0][0].keys():
                ef_inpara = [res_l[i][ief][key] for i in range(len(res_l))]
                newres[key] = np.average(ef_inpara, axis=0)

            newres_l.append(copy.deepcopy(newres))

        return newres_l


    def MCseries(self):
        """The main function should be called to do DFBMC simulation."""

        self.reader_trans()
        print("index, trans, scat matrix done...", file=self.fout)
        self.reader_velocity()
        print("bande, velocity done...", file=self.fout)

        if self.irrbz == 1:
            self.reader_scfout()
            self.kmap_array()
            if self.infiles_generate == 1:
                self.output_infiles()

        if self.enable_para:
            pool = multiprocessing.Pool(processes=self.Nprocess)
            res_para = pool.starmap(self.MC_para, [[] for _ in range(self.Nprocess)])
            pool.close()
            pool.join()

            self.res_series = self.gather_para(res_para)
            self.MCseries_printer()            
        else:
            if self.test_mode == 3:
                from profile import Profile
                p = Profile()
                p.run('self.MCmain(self.elecf_list[0])')
            else:
                for i in range(len(self.elecf_list)):
                    self.MCmain(self.elecf_list[i])

            self.MCseries_printer()

        